### ISSUE TITLE
NPGObjects:Classification

### ISSUE THREAD

**Issue by steads** [american-art/npg#11]
Classification: E22->P2->E55 (Classification)

**Comment by azaroth42** [comment]
It would be good to map to AAT for these as there are a limited number of values:
- Art Implement
- Book
- Bound Object
- Coin
- Collage
- Decorative Arts
- Document
- Drawing
- Medal
- Other
- Painting
- Photograph
- Photographic Negative
- Print
- Printing Surface
- Sculpture
- Silhouette
- Time-based Media

**Comment by si-npg** [comment]
Done--sent a spreadsheet to Kate Blanche this morning.

**Comment by si-npg** [comment]
NPG also has indexed data for what are basically sub-classifications. It is included in the NPGObjThesTerms table where ThesXrefType is "Other Classification".

**Comment by rhao** [comment]
Are you suggesting having multiple E22 in this model? Right now, it's E22 -> P2 -> E55_Type, and the type is mapped to the Classification data. However, in your suggestion, are you saying the E55_Type should be the literal "Classification", and the E22 is tied to the Classification data, which should then be tied to the top-level E22? If so, how should the top-level E22 relate to the Classification E22? Am I misunderstanding? Or is how it's currently mapped acceptable?
