### ISSUE TITLE
NPGObjects:Dated

### ISSUE THREAD

**Issue by steads** [american-art/npg#13]
Dated: This seems to be an E62 String containing a textual statement about the production of the object in the collection. I suspect that different meanings can be attached to this depending on the nature of the object. Again if the resources for a full analysis of classification and medium are available then more meaning might be extracted from the varied content of this field. If not then:-
E22     ->P3 ->E62 String 
    ->P3.1 -> E55 Type {Production Date Statement}

**Comment by azaroth42** [comment]
@steads Could you expand that into triples for us please?

```
_:x a E22_MMO ;
  p3_has_note [
    a E62_String ;
    ??? "1951 (printed 1983)" ;
    p2_has_type [
       a E55_Type ;
       ??? "Production Date Statement" ] ]
```

That seems ... awfully long winded compared to something like:

```
_:x a E22_MMO ;
  dcterms:created "1951 (printed 1983)" .
```

Which has the same expressivity.

**Comment by steads** [comment]
How you chose to implement properties of properties is up to you. The CRM-SIG recommended best practice is to use an intermediary entity. This is covered in the minutes of SIG meetings. Sorry cannot point to it more precisely but have a poor internet connection at the moment.

**Comment by steads** [comment]
The reference to using intermediary nodes is in http://www.cidoc-crm.org/docs/31st-meeting-presentations/CRM_FOL_CM_part_1.pdf on page 20 Heading: Meta-properties

**Comment by si-npg** [comment]
Begin Date and End Date are the fields used for searching and indexing in our database. Our registrars decided they wanted certain later prints and casts to index on the dates of the original works, but they needed further explanation to be included in the date label (Dated field). In this case, both dates are included again in a separate field called "Historical Dates", which I did not export.
Generally, the Dated field is either the same as Begin Date and End Date--or--if Begin Date and End Date are different, the Dated field clarifies the span.
