### ISSUE TITLE
NPGObjects:DateBegin and DateEnd

### ISSUE THREAD

**Issue by steads** [american-art/npg#14]
DateBegin and DateEnd: The mapping shows the path as 
E22 ->P108i ->E12 [Object] ->P4 ->E52     ->P82a ->E61 [DateBegin]
                ->P82b ->E61 [DateEnd]
This would be correct if the Dated field was about the production of the object in the collection. However, in several cases the Dated field and its interpretation in the DateBegin and DateEnd fields are not consistent with this interpretation. For instance:-
NPG.83.188.10   1951 (printed 1983) 1951    1951
This suggests the item in the collection was created in 1983 from a negative that was created in 1951 but the DateBegin and DateEnd are for an object created in 1951.
And:-
NPG.65.12.1 1966 cast after 1944 original   1944    1944
Again this suggests that the item in the collection was created in 1966 from an original created in 1944 but the DateBegin and DateEnd are for an object created in 1944. 
There are also inconsistencies in how the boundaries have been set for circa dates (noted by a “c.” in the Dated field) and date ranges and circa date ranges. This should probably be addressed during data cleaning/enrichment.
I would therefore be very cautious of these fields until a complete analysis of the Dated field has been completed as in several cases they are probably associated with events other than the production of the object in the collection. 
A final note the Properties P82a and P82b are not part of the CRM standard itself: they are a CRM-SIG approved RDF implementation of the standard. This is nothing to get hung up about; all E61 Time Primitives have to be locally implemented and this implementation choice has the advantage of being one that has been considered Good Practice by the SIG.

**Comment by azaroth42** [comment]
This opens the question of whether the Thing being described is the Creative Work (which occurred in 1951 when the photograph was taken)  or the Physical Object (which was created from the negative in 1983).  In order to properly model the situation, there would need to be two separate resources the Work and the Item (in FRBR terms), or in CRM something like:

```
_:x a E22_MMO ;
  dcterms:created "1983" ;
  p65_shows [
    a E36_Visual_Item ;
    dcterms:created "1951" ] .  
```

(With dcterms:created as shorthand for a creation event with a date time associated)

**Comment by steads** [comment]
You a correct in your assertion that you have an instance of E22 Man-Made Object related via P65 shows visual item (is shown by) to an instance of E36 Visual Item. However the reference to the same dcterms :created for both muddies the water somewhat as the instance of E22 Man-Made Object was made in an instance of E12 Production and the E36 Visual Item in an instance of E65 Creation. E12 and E65 have different semantics. In fact the taking of the original photograph was simultaneously an instance of E12 Production (of the negative) and an instance of E65 Creation (of the immaterial object carried by the negative). This should be handled by multiple instantiation.

**Comment by si-npg** [comment]
NPG does not use this nonstandard practice for copies or replicas made by artists. We only break the rules for photo reprints and later casts of sculpture that are sort of not really works of art in themselves (pretend I didn't say that.)
Copying part of my comment from the Dated field (#13): Begin Date and End Date are the fields used for searching and indexing in our database. Our registrars decided they wanted certain later prints and casts to index on the dates of the original works, but they needed further explanation to be included in the date label (Dated field). In this case, both dates are included again in a separate field called "Historical Dates", which I did not export.
