### ISSUE TITLE
NPGObjects:Dimensions

### ISSUE THREAD

**Issue by steads** [american-art/npg#15]
Dimensions: Again there is a lot of variability in the format and also probably in the intended meaning of the content of this field. With sufficient analysis and processing 4 or 6 instances of E54 Dimension could be extracted from each entry in this field: metric and imperial; length, breadth and, for 3D works, depth. Some of the text flags present in the field might be used to qualify (with an E55 Type) the nature of an associated E16 Measurement or if they represent a reference to a documented technique then by using P33 used specific technique E29 Design or Procedure. Else treat as a string:-
E22     ->P3 ->E62 String 
    ->P3.1 -> E55 Type {Dimensions Statement}

**Comment by rhao** [comment]
I'm not sure I'm following. Currently, it's E22 -> P43_has_dimension -> E54_Dimension. Are you saying that the data is actually multiple instances of E54_Dimension, so grouping it under one is too specific for the data? That makes sense. If so, I don't totally understand the proposed solution. What data should be tied to the E62_String and E55_Type? There's only one column of data, so I assume you don't want the same data tied to both, and I'm not understanding what those objects represent?

Given the nature of the data, I think it's better not to attempt to parse the data and break it into different objects, but instead find one that's general enough to fit the entire column, so I guess I'm confused about why you have 2 objects after E22 for the 1 column.

**Comment by steads** [comment]
P3.1 is a property of a property that links to an instance of E55 Type. In this case I  suggested that the value of E55 Type should be the literal "Dimension Statement" to indicate that the instance of E62 String that is attached to the instance of E22 Man-Made Object is a "Dimension Statement". The content of your column of data would then be the instance of E62 String. I think Karma implements E62 String as some kind of literal but I will leave a Karma expert to confirm this.

**Comment by rhao** [comment]
Great, that makes sense, thanks! Will continue the E62_String discussion in #57
