### ISSUE TITLE
NPGObjects:CreditLine

### ISSUE THREAD

**Issue by steads** [american-art/npg#16]
CreditLine: Doesn’t seem to have a mapping. There are hidden events in many of the statements that could, with further analysis, produce a number of instances of E7 Activity and instances of E39 Actor with P14.1 roles in the instances of E7 Activity. If the resources are not available then:-
E22     ->P3 ->E62 String 
    ->P3.1 -> E55 Type {Credit Line Statement}

**Comment by rhao** [comment]
Great, mostly updated as String and Type, just waiting for #57 to finish implementing
