### ISSUE TITLE
NPGTitles:Title

### ISSUE THREAD

**Issue by steads** [american-art/npg#18]
Title: This is correctly mapped as:-
E22 ->P102 ->E35
Care should be taken with translation though as titles that are made up of people’s names should not be translated, for instance George Eats Alone should not be translated as George Mange Seul; E35 normally implies translation is acceptable.

**Comment by edgartdata** [comment]
How can we make sure that these titles have a note with "translation not recommended"? I suspect that this would be useful to NPG.

**Comment by azaroth42** [comment]
Also, where does the actual title string go?  rdfs:value? or P3_has_note ?  If it's in the note field, how do you then have a note about a title?

**Comment by steads** [comment]
The E35 Title is the endpoint of the mapping. So it does not carry on via P3 to an instance of E62 String. You might want to be a bit stronger than adding a note to the instance of E35 Title and actually add P2 has type E55 {Not translatable}. Another alternative is to make the title less ambiguous ("Portrait of George Eats Alone") but I am sure that would break all the co-references from other sources.
My rdf is a bit rudimentary but something like this snippet (based on 3M output) would probably do the trick: 


```
<crm:P102_has_title>
  <crm:E35_Title rdf:about="uuid:AA">
    <crm:P2_has_type>
      <crm:E55_Type rdf:about="http://NPG.org/title-types/Not%20Translatable"/>
    </crm:P2_has_type>
    <rdfs:label>George Eats Alone</rdfs:label>
  </crm:E35_Title>
</crm:P102_has_title>
```

**Comment by edgartdata** [comment]
I really like  E35 Title  P2 has type E55 {Not translatable}.

**Comment by si-npg** [comment]
I could include our "Title Type" field, and we could apply the E55 {Not translatable} label for those with Title Type=Sitter, i.e. those with titles that are simply the sitter's name. That would still leave some problems, e.g. "The Attack on Sitting Bull's Cabin" (Title Type=Title), but only a few. Is it possible to apply the E55 {Not translatable} label manually to individual records? Note: we also have some foreign language titles (usually with Title Type=Alternate Title.)

**Comment by rhao** [comment]
I added E55_Type with value "Not Translatable" as a type of E35_Title.
