### ISSUE TITLE
Model of credit line should preserve the credit line as is

### ISSUE THREAD

**Issue by szeke** [american-art/npg#2]
Currently, the model splits the credit line. The question is whether it should be one field only, and how it should be modeled.

**Comment by kateblanch** [comment]
Related to this issue is whether the "owner" of the  artwork can be extracted from CreditLine, is a separate data point is needed to provide the ownership of each artwork?

**Comment by caknoblock** [comment]
I think we should have a list of items that all museums should provide, such as owner.  If the museum owns everything they submit, then they can just tell as that and we can add that field.

**Comment by VladimirAlexiev** [comment]
Where is that? I can't find it in directory NPGObjects.
Since they all start with "National Portrait Gallery, Smithsonian Institution", I think this should be made out as a current_owner link; the rest as P3_has_note (or better yet, a custom prop crmx:P3_credit_line)

**Comment by YinyiUSC** [comment]
The credit line information is not included in the current model, but you should be able to find it in the original data set.
