### ISSUE TITLE
NPGExhibitions:BeginISODate

### ISSUE THREAD

**Issue by steads** [american-art/npg#25]
BeginISODate: These are generally not in ISO format (http://imgs.xkcd.com/comics/iso_8601.png). There are 3 BeginISODate that do not have a day element (but are in ISO format!): if these are to be mapped with P82a_begin_of_the_begin then they could be reasonably set to the first of month or left with no day element. Remember that P82 is “at some time within”.
The full mapping would then be:-
E22     ->P16i ->E7 [Exhibition] ->P4 ->E52 ->P82a ->E61 [BeginISODate]
    ->P16.1 ->E55 {Exhibit}
A final note the Properties P82a and P82b are not part of the CRM standard itself: they are a CRM-SIG approved RDF implementation of the standard. This is nothing to get hung up about; all E61 Time Primitives have to be locally implemented and this implementation choice has the advantage of being one that has been considered Good Practice by the SIG.

**Comment by VladimirAlexiev** [comment]
See #4, which has been closed, IMHO unjustly

**Comment by rhao** [comment]
I mapped the date with the path described by steads. See #4 for my solution to the xsd date format issue.

**Comment by VladimirAlexiev** [comment]
@rhao can you paste some Turtle here so we can validate? In particular:
- don't use E61 (use directly a xsd:date or xsd:gYearMonth literal).
- if there's a single date, use P82 instead of P82a/b
- what prop names do you use for P82a/b
- how do you express "Exhibition"
