### ISSUE TITLE
NPGExhibitions:EndISODate

### ISSUE THREAD

**Issue by steads** [american-art/npg#26]
EndISODate: These are not in ISO format (http://imgs.xkcd.com/comics/iso_8601.png).
There are 10 dates which would seem to be planned end dates (dates in 2017-2019). These have a different nature to the end dates that are historical facts but might be useful for some purposes as modelled. However the data will introduce problems in the future as it will give rise to two versions of history: the planned and the actual and no way of knowing from the data which is which. It would be better to select a time primitive with a concept of ongoing at the time of export and to map the planned end dates separately. This is currently an open item in the SIGs research agenda and contributions on this topic would be welcomed.
There are 10 dates which would seem to indicate ongoing exhibitions with no planned end date (dates in the year 3000). There is some inconsistency in them as 8 indicate the 1st Jan and two the 31st!
There is one exhibit (ID 968) that is entitled “Test Exhibition” and has and end date in the not too distant past (Oct 2020). Is this a real exhibit or an artefact of system testing? If it is a real exhibit then it should be grouped with the other 10 exhibitions with planned end dates (see above). If a system test then I would suggest not exporting it.
There are 25 Exhibitions were the end date is “NULL”. If this indicates incomplete knowledge then an estimate would normally be acceptable. Remember that P82 is “at some time within”.
E22     ->P16i ->E7 [Exhibition] ->P4 ->E52 ->P82b ->E61 [EndISODate]
    ->P16.1 ->E55 {Exhibit}
A final note the Properties P82a and P82b are not part of the CRM standard itself: they are a CRM-SIG approved RDF implementation of the standard. This is nothing to get hung up about; all E61 Time Primitives have to be locally implemented and this implementation choice has the advantage of being one that has been considered Good Practice by the SIG.

**Comment by VladimirAlexiev** [comment]
See #4, which has been closed, IMHO unjustly

**Comment by rhao** [comment]
It looks like the V2 of the data was changed to remove some of the cases you're talking about - for example, ID 968 is no longer in the dataset. How do you know that it's 2017? I only see years with 2 digits. See #4 for my temporary solution to this. Do you have a suggested estimate for NULL dates? Right now I just make them empty strings because I didn't want to make the data more specific than it actually is.

**Comment by VladimirAlexiev** [comment]
Where do you see partial dates? When I open the XSLX in Excel, I see full dates. 
I think that your interpretation "17 and further are interpreted as 1917" is wrong: it's clear there are some future dates in this table, eg
![image](https://cloud.githubusercontent.com/assets/536250/19304151/3c19a216-9074-11e6-8a2f-ac87b1181fb1.png)
9/11 did not happen in 19xx so clearly the dates 20xx are correct.

Wikipedia calls this "Date windowing", but I couldn't find an accepted best practice for it.
