### ISSUE TITLE
Mapping NPGObjects: Medium to E57-Material

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/npg#3]
I used to map Medium to E29 Design or Procedure http://139.91.183.82:8888/drupal/Entity/E29-Design-or-Procedure/Version-6.0, but I've recently been told that it would be better to separate design and material, therefore I've adopted E57 Material instead http://83.212.168.219/CIDOC-CRM/Entity/e57-material/version-6.0. E22 Man-made Object is then be to E57 Material via P46 is composed of. 

Please let me know if there is a better practice for mapping the Medium field. Thanks!

**Comment by VladimirAlexiev** [comment]
- Some of them definitely don't sound like materials, eg in "Hand-colored lithograph on paper" the part before "on" is a technique not material.
- So it's better to map it to P32_used_general_technique. Please note that's E55 not E29: the latter is reserved for specific instances of eg architectural plans.
- If you stick with E57 Material, of course you must use P45_consists_of and not P46_is_composed_of

**Comment by si-npg** [comment]
Also added this comment to #12:
I provided indexed data for both medium support in the ObjThesTerms table of my updated data set.

**Comment by rhao** [comment]
Closing this issue because it is also discussed in #12
