### ISSUE TITLE
NPGObjConXrefs:ObjectID

### ISSUE THREAD

**Issue by steads** [american-art/npg#32]
ObjectID: This is a temporary system identifier used to tie records together between files and as such there is no need to map it. A lot of the entries point to ObjectIDs that do not exist in NPGObjects. It would seem rather pointless to export this data as it does not tie back to any objects currently in the collection catalogue. Is this as a result of backlog or disposals?

**Comment by VladimirAlexiev** [comment]
Right! 
NPGObjConXrefs refers to 120879 ObjectID while NPGObjects has only 16562.

I would guess that NPGObjects was filtered by some criteria (eg publicly viewable, or sampling of a certain kind of objects), but the same filtering was not applied to NPGObjConXrefs.

NPGObjConXrefs must be filtered to only ObjectID existing in NPGObjects.
