### ISSUE TITLE
NPGObjConXrefs:RoleID

### ISSUE THREAD

**Issue by steads** [american-art/npg#33]
RoleID: This is a pointer to a controlled vocabulary that has not been supplied. It has four possible values (1, 19, 102, 106) and the rest of the values in this table show that the four different values indicate completely different mappings in the CRM.
RoleID= “1” would generally seem to produce one of the mappings partially represented in the model PDF (partially because the P14.1 is not shown in the PDF):-
E22 ->P108i ->E12 [Object]  -> P14 -> E39
                ->P14.1 -> E55 {Artist:}
However there are 9175 records that do not fit this mapping as the Prefix field contains other information. The use of a colon on the end of “Artist” is presumably an artefact of this being part of a display system that neglected to supply formatting at the display layer but rather required it at the data layer. I would suggest that this is removed during export.
RoleID= “19” would generally seem to produce one of the mappings represented in the model PDF:-
E22 ->P62 ->E21
However there are some of the Constituents that are actually instances of E39 Actor as they represent more than one person.
So it would be in that case:-
E22 ->P62 ->E39 
This mapping could also be true (it might not be if the artist worked from images of the depicted) and possibly useful for integration of who was where and when:-
E22 ->P108i ->E12 [Object]  -> P14 -> E39
                ->P14.1 -> E55 {Sitter:}
In addition there are 2778 records that do not fit this mapping as the Prefix field contains information other than “Sitter:”.

**Comment by VladimirAlexiev** [comment]
See #49 and the pivot table there
