### ISSUE TITLE
NPGObjConXrefs:DisplayOrder

### ISSUE THREAD

**Issue by steads** [american-art/npg#34]
DisplayOrder: This is a system implementation instruction and as such has no need for a mapping.

**Comment by VladimirAlexiev** [comment]
From my work with the Getty, I disagree. Sometimes art researchers are very particular about the order in which things are listed, and this has semantics. 
Some examples of objects with several associations having the same Role. Maybe the order of these associations is significant. 
- objectId=4638 has 34 "Sitters" (eg the order could be left-to-right)
- objectId=17216 has 159 "Sitters"
- objectId=118068 has 2 "Possible Attributions" (eg first Attribution could be more likely than the second)
- objectId=123605 has 3 "Associated persons"

Even for different roles, art researchers sometimes want to see them in a particular order.

This can be mapped as E13_Attribute_Assignment over the relation, using the extension property `crmx:display_order` we've defined for CONA and JPGM

**Comment by steads** [comment]
If there are semantics in the order then this needs to be made clear by using the appropriate CRM mechanism to show the semantics. So for instance the two "Sitters" examples above would be best modelled using CRMdig  and the "possible attributions" by using CRMinf.

**Comment by VladimirAlexiev** [comment]
What properties from CRMdig and CRMinf express ordering?

**Comment by steads** [comment]
The semantics are not actually about ordering. The ordering is being used to express the real semantics. So in the sitters example the semantics is about who is depicted adjacent to other subjects. The relative strength of possible attributions is about levels of believe.

**Comment by VladimirAlexiev** [comment]
Now you're ascribing meaning to the DisplayOrder field that may or may not be there. Maybe sitters are listed by importance, how would you know.
I'm just saying if that field is present, we should emit it, because at least in some cases it has meaning.

**Comment by steads** [comment]
In the CRM if we do not understand it we do not map it. This is axiomatic to the development of the CRM. Local solutions are fine. See our forthcoming CAA paper for guidelines.

**Comment by VladimirAlexiev** [comment]
Getty asked me to map it for CONA and JPGM, so they value it. As I said above, art researchers want the particular order.
