### ISSUE TITLE
NPGObjConXrefs:Prefix

### ISSUE THREAD

**Issue by steads** [american-art/npg#36]
Prefix: This field has not been mapped. However, it is a field that qualifies different relationships between the instance of E22 Man-Made Object and the E39 Actors identified in NPGConstituents. Unfortunately this has not had a controlled vocabulary used with it and so there are many variant spellings of the same term. Once this has been addressed then detailed analysis of this field, RoleID and Suffix will be required to determine the actual CRM paths that are described.

**Comment by VladimirAlexiev** [comment]
Out of 86 values, 12 should be merged (those marked \* below). This is pretty much controlled.

```
Addressee:
Agency:
*Alledged:
Alleged:
Animator:
Artist:
Assisted by:
Associated Institution:
Associated Person:
*Atribution:
*Attributed to:
*Attributed:
*Attribution
Attribution:
Attribution: Studio of
*Author
Author:
Begun by:
Cartographer:
Carved by:
Cast after:
Cast by:
Chased by:
Composer/Lyricist:
Composer:
Copy after (formerly):
Copy after:
Corrections by:
Derived from:
Designer:
Die cutter:
Drawn by:
Editor:
Engraved by:
Finished by:
Follower of:
Forgery after:
*Formally alleged:
*Formally attributed:
Former attribution:
Former possible identification:
Formerly alleged:
Foundry:
Frame maker:
Illustrator:
Inventor:
Lithographer:
Maker:
Manner of:
Manufacturer:
NULL
Other attribution:
*Possbily by:
Possible attribution:
Possible author:
Possible copy after:
Possible forgery after:
Possible sitter:
Possible studio:
Possibly after:
Possibly aided by:
Possibly attribution:
*Possibly by:
Possibly derived from:
Possibly:
Presented by:
Printer:
Probably after:
Probably:
Producer:
*Publication:
*Published by:
Publisher:
Repainted by:
Reproduction after:
Researcher:
Retouched by:
School of:
Signer:
Sitter:
Studio of:
Studio:
Subject:
Sung by:
Translator:
Workshop of:
```

**Comment by steads** [comment]
Having two entries like this is the definition of NOT having a controlled vocabulary!!
*Alledged:
Alleged:

**Comment by VladimirAlexiev** [comment]
I mean that matching 12, then designing "CRM casing" for the remaining 74, is quite doable.  Or at least should be done for the top 10-20, catching more than what Artist and Sitter do (90%)
