### ISSUE TITLE
NPGObjConXrefs:Suffix

### ISSUE THREAD

**Issue by steads** [american-art/npg#37]
Suffix: This field has not been mapped. However, it is a field that qualifies different relationships between the instance of E22 Man-Made Object and the E39 Actors identified in NPGConstituents. The field shows many artefacts of this being part of a display system that has required formatting at the data layer. I would suggest that this is removed during export.

**Comment by VladimirAlexiev** [comment]
This field is not mapped to anything. But the number of cases is not so great, so it's possible to analyze and map to something.

I analyzed the occurrences of Suffix. There are 67 values, the values with >=2 occurrences are:

```
 262237 NULL
    338 (Photographer)
     79 (Attribution)
     33 (Forger)
     16 (Sculptor)
     16 (Engraver)
      8 (British)
      7 (Miniaturist)
      6 (Daguerreotypist)
      5 (Former attribution)
      3 (English)
      2 (Russian)
      2 (Printmaker)
      2 (Lithographer)
      2 (Forgers)
      2 (Chinese)
      2 (?)
```

Then I analyzed the co-occurrence of the most populous Suffix (Photographer) with Prefix:
- most often (334) it's

```
  Copy after:   (Photographer)
```
- but there are also a few other occurrences:

```
  Derived from: (Photographer)
  Artist:   (Photographer)
  Probably after:   (Photographer)
```
