### ISSUE TITLE
NPGConstituents: Use of E39 Actor

### ISSUE THREAD

**Issue by steads** [american-art/npg#38]
The mapping to E39 Actor is correct as there are both individuals (E21 Person) and groups (E74 Group). However this makes the mapping rather weak as the use of the superclass restricts the utility of the resulting data.

**Comment by VladimirAlexiev** [comment]
Right! 
I checked all values of column Institution, and indeed they represent Groups. With the possible exceptions of the following (most of them are not Persons either)

Ackerman
Admiralty Arch
Anonymous Loan to the Boston Athenaeum
Antoinette
Benjamin Harrison Presidential Site
BELL, RON
Belgrave Square
Violinist
Widow
William
You Can Please Some Of The...
Young

**Comment by VladimirAlexiev** [comment]
As mentioned in #41, #42 this should be done. It's not hard to do: switch on presence of Institution field.

Steve, maybe change the title to "... use E21 Person vs E74 Group"

**Comment by edgartdata** [comment]
It seems that there is nothing for NPG to do here since they provided a separate Institution column with the names of the institutions and the value NULL for instances when the field does not apply to persons.
