### ISSUE TITLE
NPGConstituents:BeginDate

### ISSUE THREAD

**Issue by steads** [american-art/npg#41]
BeginDate: is currently mapped to:-
E39 ->P98i ->E67 ->P4 ->E52 ->P82 ->E61
This seems to be correct for those instances of E39 that are actually instances of E21 Person but not for those that are instances of E74 Group. P98 may not be used with E39.

**Comment by VladimirAlexiev** [comment]
Right! Once #38 is done, for Groups you should use P95i was formed by and E66 Formation.
If you can't do #38 then you should use the more generic E63 Beginning of Existence

**Comment by steads** [comment]
Absolutely the property would be P92 brought into existence (was brought into existence by). However as we  said for #42 going up to this general level is quite weak.
