### ISSUE TITLE
NPGConstituents:EndDate

### ISSUE THREAD

**Issue by steads** [american-art/npg#42]
EndDate: is currently mapped to:-
E39 ->P100i ->E69 ->P4 ->E52 ->P82 ->E61
This seems to be correct for those instances of E39 that are actually instances of E21 Person but not for those that are instances of E74 Group. P100 may not be used with E39.

**Comment by VladimirAlexiev** [comment]
Right! Once #38 is done, for Groups you should use P99i was dissolved by and E68 Dissolution.
If you cannot do #38 then you must use the generic E64 End of Existence.

**Comment by steads** [comment]
Spot on and the property would be P93 took out of existence (was taken out of existence by). Going up to this general level is quite a weak mapping though so to complete #38 would be much stronger.
