### ISSUE TITLE
NPGConstituents:Use of F51 Pursuit

### ISSUE THREAD

**Issue by steads** [american-art/npg#45]
For instances of E74 Group the FRBRoo Class F51 Pursuit might be useful once a clear separation between Instances of E21 Person and E74 Group has been arrived at.

**Comment by VladimirAlexiev** [comment]
What would it be used for? In the excel sheet I don't see anything like "field of activity", and there's only one pair of dates (presumably birth/death)

**Comment by steads** [comment]
You have to look at the actual data not just the field names. Constituent entries 2123 and 2372 are examples where F51 would be appropriate.

**Comment by VladimirAlexiev** [comment]
I checked all 105144 records for words expressing activity type:

``` sh
>grep -Ec "(Active|acitve|actitve|active|fl.|flourished)" d1
1328
>grep -Ec "(born|founded|established)" d1
7171
```

The first group should be mapped to "performed F51 Pursuit".
The second group is already captured by classes Birth / Foundation, so nothing extra is needed.

There are more words that express date qualifiers:
- qualifier: before/after/early/mid/late/second quarter
- open end date: "present"
- uncertainty: abt.|c.|\?

**Comment by si-npg** [comment]
Constituent Type:  Individual = Person and Institution = Group
Begin Date = Birth Date and End Date = Death date for individuals, except when the corresponding Display Date includes any text other than the dates themselves, e.g. "c." or "20th Century" or "active". In those cases, the Begin and End Dates are begin and end search dates, i.e. estimates for search purposes.

**Comment by VladimirAlexiev** [comment]
The mapping for birth/death and formation/dissolution vs active is quite different, 
since CRM doesn't have classes for "Life of a person" or "existence of a group":

``` turtle
<constituent/69> a crm:E21_Person;
  crm:P3_has_note "1744–1831";
  crm:P98i_was_born <constituent/69/birth>;
  crm:P100i_died_in <constituent/69/death>.
<constituent/69/birth> a crm:E67_Birth; crm:P4_has_time-span <constituent/69/birth/date>.
<constituent/69/birth/date> a crm:E52_Time-Span; crm:P82_at_some_time_within "1744"^^xsd:gYear.
<constituent/69/death> a crm:E69_Death; crm:P4_has_time-span <constituent/69/death/date>.
<constituent/69/death/date> a crm:E52_Time-Span; crm:P82_at_some_time_within "1831"^^xsd:gYear.

<constituent/70> a crm:E21_Person;
  crm:P3_has_note "active 1775 - 1806";
  crm:P14i_performed <constituent/70/active>.
<constituent/70/active> a frbroo:F51_Pursuit; crm:P4_has_time-span <constituent/70/active/date>.
<constituent/70/active/date> a crm:E52_Time-Span;
  crm:P82a_begin_of_the_begin "1750"^^xsd:gYear;
  crm:P82b_end_of_the_end "1850"^^xsd:gYear.
```

**Comment by si-npg** [comment]
When the display field for life dates for an individual says "active...", the corresponding Begin and End Dates should represent a search span for the constituent's whole life, i.e. they still represent estimated life dates...though I jut checked and found that we have some data cleanup to do here.

**Comment by VladimirAlexiev** [comment]
To clarify, you can have "active 1775 - 1806" but the begin/end date range will be wider (birth/death)?
Then frbroo:F51_Pursuit doesn't apply, unless someone parses out years out of displayDate.

**Comment by si-npg** [comment]
Correct--the begin and end dates for the constituent you are referring to are 1750 and 1850.

**Comment by steads** [comment]
The 1328 "Active|acitve|actitve|active|fl.|flourished" that @VladimirAlexiev found could/should be "emitted" as instances of F51 Pursuit as well. The data is there and shouldn't be too difficult to parse the dates out of the displayDate.
