### ISSUE TITLE
NPGObjConXrefs: map RoleId and Prefix

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/npg#49]
Currently the mapping maps only Prefix, and then only 2 values from it: 'Artist:' and 'Sitter:' (see NPGObjConXrefs-report.md). This takes care of 111020+125936=236956 rows, or 90.1% of the total 262833.
But it leaves a long tail of 10% of relations unmapped, i.e. just skips them. I made a pivot and shared it here: https://drive.google.com/folderview?id=0B7BFygWDV2_PYS0xMVR0V3pxVXc&usp=sharing:

![image](https://cloud.githubusercontent.com/assets/536250/16833214/f9eac4c8-49b6-11e6-9bc0-47c594d2cce7.png)
- Explain what the different RoleId mean (1 19  102 106)
- Decide appropriate mappings for the top rows. Eg if we map the top 21, that will map 25.3k more rows, bringing the coverage to 99%.

Eg "Copy after" is very valuable art research info.

Related to #36 and possibly #37

**Comment by steads** [comment]
Nice!
All the "possible" etc should be mapped assuming it to be true and then using CRMinf to capture the level of belief in the statement.

**Comment by azaroth42** [comment]
Can we please avoid using CRMinf as one level of complexity too many?

**Comment by VladimirAlexiev** [comment]
Another option would be to use [PX_likelihood](https://confluence.ontotext.com/display/ResearchSpace/BM+Association+Mapping+v2#BMAssociationMappingv2-Probably%2FUnlikelyProducedBy) as used by BM/ResearchSpace. It's a subprop of P2_has_type, applied on EX_Association, which is a subclass of E13

**Comment by steads** [comment]
CRMinf describes the real complexity of argumentation. If you do not want this complexity you are free to use local solutions but they will be just that "local".

**Comment by si-npg** [comment]
As with issue #39, many of these issues do not exist with our updated data. the Prefix field is populated for every ConXref in our updated data.
The four role IDs are as follows: 1=Artist, 19=Sitter, 102=Secondary Artist/Maker and 4=Associated Person/Institution. Sorry I did not submit our Roles table to clarify that.
Prefix, when it is not the same as the Role, is a more specific descriptor, like a sub-role.

**Comment by VladimirAlexiev** [comment]
@si-npg:
- There are 4 values Suffix=" " that should be treated as (or replaced with NULL).
- what is Role=106? Guess "Associated", seems 106 is now used instead of 4
- Could you please explain what eg this situation means:

```
object=O, constituent=C, prefix=Copy after:, suffix=(Photographer)
```
- could it be that "Cast after:" and "Copy after:(Sculptor)" mean the same?
- should Role be ignored in the mapping (as it currently is)? If not, please explain it; eg "Publisher:" is used with 1, 102, 106)

Here is the updated pivot:
![image](https://cloud.githubusercontent.com/assets/536250/17510044/c5935cde-5e25-11e6-8cba-2893e6564191.png)

**Comment by si-npg** [comment]
ROLES:  1=Artist, 19=Sitter, 102=Secondary Artist/Maker and 106=Associated Person/Institution
Most objects have a Sitter OR Associated Person/Institution; most have at least one Artist, and some have Secondary Artists/Makers too--often multiples.
Cast after: is used for a later cast after an original sculpture; Copy after: (Sculptor) is a copy by one sculptor--an actual artist--after another.
Prefix is not a controlled field. We do our best to keep it clean/consistent, but it's not perfect. It's used to give further explanation to the very broad Role term. For human-readability, it can always be used instead of Role, but we do rely very heavily on the Rold field itself.

**Comment by edgartdata** [comment]
@si-npg Great explanation of the implicit conventions hidden in plain language with:
Cast after: is used for a later cast after an original sculpture; Copy after: (Sculptor) is a copy by one sculptor--an actual artist--after another.
These would be modeled differently with the latter introducing the notion of influence from the original artist onto the artist who is copying the sculpture. I guess "cast after" could use P130_shows_features_of the original sculpture to the new cast?

**Comment by VladimirAlexiev** [comment]
@si-npg What does "object=O, constituent=C, prefix=Copy after:, suffix=(Photographer)" mean?
Does it mean that C created a photograph (not tracked in your system) that is a copy after O?
Or is O the identifier of the new object (the photograph), and then how is the old object identified?

About roles: I'm puzzled why the same Prefix is sometimes used with several Roles.
- "Publisher" is most often used with role 102 "Secondary maker" and that makes sense.
- But what does it mean "Publisher" with role 1 "Artist"? Is it different from the previous bullet?
- And what does it mean "Publisher" with role 106 "Associated"?

@edgartdata: "Copy after: (Sculptor)" will map to crm:P130_shows_features_of. "Cast after" will map to more than that.
Here's a proposed mapping, I call these "CRM Casing". We have plenty of examples like this for CONA associative (artwork) relations:
- "Copy after: (Sculptor)"

``` turtle
<newSculpture> crm:P130_shows_features_of <oldScuplture>.

<newSculpture> crm:P108i_was_produced_by <newSculpture-production>.
<newSculpture-production> crm:P14_carried_out_by <sculptor>.
```
- "Cast after"

``` turtle
<newSculpture> crm:P130_shows_features_of <oldScuplture>.

<oldSculpture> crm:P108i_was_produced_by <oldSculpture-production>.
<oldSculpture-production> crm:P16_used_specific_object <oldSculpture-mold>.
<oldSculpture-mold> a crm:E22_Man-Made_Object;
  crm:P2_has_type aat:300024814. # mold (shaping equipment), aka cast (mold shaping equipment)

<newSculpture> crm:P108i_was_produced_by <newSculpture-production>.
<newSculpture-production> crm:P14_carried_out_by <sculptor>;
  crm:P16_used_specific_object <oldSculpture-mold>.
```

**Comment by VladimirAlexiev** [comment]
@azaroth42 @steads @workergnome @edgartdata @si-npg 
Figure below made from above turtle using my [rdfpuml](http://vladimiralexiev.github.io/pres/20160514-rdfpuml/) tool:

![image](https://cloud.githubusercontent.com/assets/536250/17563389/dccf8aa4-5f37-11e6-9741-0fd00b75beda.png)

As I said at the LA meeting in April, I think we need to make such prototypical models for all data areas. Otherwise I'm afraid confusion will reign: we can't be discussing this museum per museum, and in github issues. We need to document an overall model.

**Comment by edgartdata** [comment]
@VladimirAlexiev I am not sure why we would not want to use P_15_was_influenced_by for **Copy after: (Sculptor)** as that qualifier clearly emphasizes the influence of one artist on another?

**Comment by steads** [comment]
```
"Copy after: (Sculptor)"
```

<newSculpture> crm:P130_shows_features_of <oldScuplture>.

<newSculpture> crm:P108i_was_produced_by <newSculpture-production>.
<newSculpture-production> crm:P14_carried_out_by <sculptor>.

This is not correct. The Copy after: (Sculptor) should be modelled with P15. This is showing the influence of a body of work or style not the copying of a particular object which is what the P130 shows.

**Comment by steads** [comment]
Spot-on @edgartdata !

**Comment by VladimirAlexiev** [comment]
@si-npg states "Copy after: (Sculptor) **is a copy**", that's why I think P130 is relevant.

I agree that P15 should also be used: but it is <oldSculpture> that influenced the creation of <newSculpture>, not the author of <oldSculpture> (only part of his work may have exerted that influence, and it could be it had several authors but only one of them had influence). The data only gives us evidence about <oldSculpture>, not other work(s) of the same author(s).

I'm puzzled that each row has only **one** objectID, @si-npg please answer [my question above](https://github.com/american-art/npg/issues/49#issuecomment-238936553)

Here's updated modeling of "cast after" including P15, how do you like it?
![image](https://cloud.githubusercontent.com/assets/536250/17580056/01aa1eb8-5fa4-11e6-949a-fc2c94fa527d.png)

**Comment by si-npg** [comment]
Q: What does "object=O, constituent=C, prefix=Copy after:, suffix=(Photographer)" mean?
Does it mean that C created a photograph (not tracked in your system) that is a copy after O?
Or is O the identifier of the new object (the photograph), and then how is the old object identified?

A: O refers to the new object, which has a different medium than the original (which is why we add a suffix in this case; normally a copy is a copy in the same medium.) So the example above describes a an object in some medium other than photography that is a copy after a photograph.

Q: About roles: I'm puzzled why the same Prefix is sometimes used with several Roles.
"Publisher" is most often used with role 102 "Secondary maker" and that makes sense.
But what does it mean "Publisher" with role 1 "Artist"? Is it different from the previous bullet?
And what does it mean "Publisher" with role 106 "Associated"?

A: Publisher in the role of artist occurs in 4 NPG objects, and I have requested that our curators to change these. (They were entered this way intenionally, but it's not necessary.) Publisher in the role of Associated Person occurrs in just 2 NPG objects, and I've already changed these, since they were just mistakes! So the Publisher prefix will not be an issue going forward. However, there may be other prifixes that are sometime used for one role and sometimes another. (I'll need to check whether any of these are included in our data set.)

**Comment by VladimirAlexiev** [comment]
@si-npg Thanks for the answers!
Just for clarity: so the old object and its creator are not mentioned in this table?

**Comment by si-npg** [comment]
The artist of the original object is entered as a "Secondary Artist" and does have a link to the object via the ConXrefs table.
The original object itself, if it is entered in the database, is linked to the copy, but those object-to-object links are not included in our exported data. Additional relevant fields that I did not export are Historical Dates, where the date of the original is entered for objects that are copies; and Related Works and/or Notes--text fields which might reference the original work.

**Comment by VladimirAlexiev** [comment]
- so I guess the two correlated records would have: 

```
"Artist:" <new artist>, "Copy after:" <old artist>
```
- but how to interpret a suffix? Should it be like this?

```
"Artist:" <new artist> "(Photographer)", "Copy after:" <old artist>
"Artist:" <new artist> "(Sculptor)", "Copy after:" <old artist>
```
- or like that

```
"Artist:" <new artist>, "Copy after:" <old artist> "(Photographer)"
"Artist:" <new artist>, "Copy after:" <old artist> "(Sculptor)"
```

Sorry to dig like this, but @azaroth42 we need to grok a similar situation for JPMG.

**Comment by si-npg** [comment]
Your second interpretation is right. We use the suffix to describe the artist of the old (original) work.

**Comment by VladimirAlexiev** [comment]
Ok. I also notice that
- Copy After goes mostly with role=102 (the old master only influenced the new work)
- but Cast After goes mostly with role=1 (the new master is a prime contributor to the new work)

Let's consider the following situation:
- `npg/constituent/1` made copies of two works by older masters:
- he made an artistic copy `npg/object/1` of a work by `npg/constituent/2`
- he made a literal copy `npg/object/2` of a work by `npg/constituent/3` from a mold (cast)

| ConXrefID | ObjectID | ConstituentID | RoleID | Prefix | Suffix |
| --- | --- | --- | --- | --- | --- |
| 1 | 1 | 1 | 1 | Artist: |  |
| 2 | 1 | 2 | 102 | Copy after: | (sculptor) |
| 3 | 2 | 1 | 1 | Artist: |  |
| 4 | 2 | 3 | 1 | Cast after: |  |

(Remember we don't have links to these older works)

It could be modeled like this. I don't quite like that it uses completely different constructs for the two cases. We could also make a P15 link in the second case.
@si-npg @azaroth42 @steads feedback is welcome!

``` turtle
<npg/object/1> crm:P108i_was_produced_by <npg/object/1-production>.
<npg/object/1-production> a crm:E12_Production;
  crm:P14_carried_out_by <npg/constituent/1>;
  crm:P15_was_influenced_by <npg/constituent/2>.
<npg/object/1/contribution/2> a crm:E13_Attribute_Assignment;
  crm:P140_assigned_attribute_to <npg/object/1-production>;
  crmx:property crm:P15_was_influenced_by;
  crm:P141_assigned <npg/constituent/2>;
  crm:P2_has_type <thesaurus/contribution/copyAfter>;
  crm:P2_has_type <thesaurus/contribution/sculptor>. 

<npg/object/2> crm:P108i_was_produced_by <npg/object/2-production>.
<npg/object/2-production> a crm:E12_Production;
  crm:P14_carried_out_by <npg/constituent/1>;
  crm:P16_used_specific_object <npg/object/2-mold>.
<npg/object/2-mold> a crm:E22_Man-Made_Object;
  crm:P2_has_type aat:300024814;
  crm:P108i_was_produced_by <npg/object/2-mold-production>.
<npg/object/2-mold-production> a crm:E12_Production;
  crm:P14_carried_out_by <npg/constituent/3>.

<thesaurus/contribution/copyAfter> a puml:Inline.
<thesaurus/contribution/sculptor>  a puml:Inline.
aat:300024814 a puml:Inline; rdfs:label "mold (shaping equipment)".
```

![image](https://cloud.githubusercontent.com/assets/536250/17854225/c8ead50c-6879-11e6-98ec-fdcbe8c1627f.png)
