### ISSUE TITLE
(!) add P2_has_type to Exhibition

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/npg#5]
Currently you make this:

```
<http://americanartcollaborative.org/npg/exhibition/13> a crm:E7_Activity ;
    crm:P1_is_identified_by <http://americanartcollaborative.org/npg/exhibition/13/appellation> ;
    crm:P4_has_time-span <http://americanartcollaborative.org/npg/exhibition/13/date> .
```

then for each object, list the exhibitions it was present at. But an object is present in many events (eg its production). So how can one find only the Exhibitions amongst them?

Add this  to each exhibition:

```
crm:P2_has_type aat:300054766; # exhibition (event)
```

**Comment by szeke** [comment]
This can be done using "Add Outgoing Literal" on the exhibition, putting the full aat URI as the value, and checking the "is URI" box

**Comment by si-npg** [comment]
NPG has 4 thesaurus terms for Exhibition Type: Permanent Collection Exhibition, Recent Acquisitions, Temporary Exhibition and Traveling Exhibition.
There are also checkboxes on our database for:  In-House Exhibition, Traveling Exhibition and Virtual Exhibition.
These are not used 100% consistently, and none have been applied comprehensively to exhibitions that existed before the fields were available to us. This is why we did not include them in our export.

**Comment by VladimirAlexiev** [comment]
`aat:300054766; # exhibition` seems to be a super-concept of all the ones you list.

re Traveling Exhibition: JPGM also have info about Venues it has visited; don't you have such info?
In JPGM the objects are linked at this "exhibition at venue" level, since the set of objects can change from venue to venue.

**Comment by si-npg** [comment]
NPG does have venues. I did not submit that data because we have not yet entered our own museum as a venue for past exhibitions that were entered on the database before we had the ability to enter venues.

**Comment by VladimirAlexiev** [comment]
This also applies to https://github.com/american-art/cbm
