### ISSUE TITLE
NPG Data Set V2: Please Commit

### ISSUE THREAD

**Issue by kateblanch** [american-art/npg#52]
For Craig and ISI Team, I just sent a pull request to American-art:master to upload the newest data set from NPG. 

Because the data was revised in May/June but didn't reach you until now, it was revised well before we established guidelines about resubmitting data, I can only suggest that your team should work with Sue on identifying which files and columns need new mappings. 

Many thanks!

**Comment by caknoblock** [comment]
Merged.

**Comment by VladimirAlexiev** [comment]
User beware: https://github.com/american-art/npg/blob/master/NPG_LOD.zip is updated, but the directories in this repo are not
