### ISSUE TITLE
Missing terms from CIDOC-CRM ontology

### ISSUE THREAD

**Issue by rhao** [american-art/npg#57]
I noticed in some issues, such as #15 and #16 the suggestion includes E62_String in between E22 and an object (that I'm guessing maps to the data column). As commented on in #15 I'm not totally sure what this intermediate E62_String represents. Also, given the ontology loaded in karma, I can't create E62. @mayaram00 also had this issue I think. Are we missing any files that prevent us from making instances of E62?

**Comment by rhao** [comment]
The first part of my question was answered in #15 so that's resolved.

I still need to know how to map E62_String, since the CIDOC-CRM E62_String doesn't show up in karma. If I search "string" under "Literal Type", I see xsd:string and xsd:normalizedString, but if I try to use that, I get the error "Semantic type not valid!" Suggestions? @caknoblock

**Comment by rhao** [comment]
So far, I've noticed that karma is missing E61_Time_Primitive, E62_String, P16.1_mode_of_use, P3.1, and I need to use all of these.

**Comment by mayaram00** [comment]
I also have this issue for several of the Autry datasets.

**Comment by rhao** [comment]
E61 and E62 are resolved.

The ontology is missing P16.1 and P3.1. @steads - how should we handle the cases where you suggested using these properties?

**Comment by steads** [comment]
The CRM is not missing them! But your implementation might not be geared up for them directly. Try using the CRMpc extension. This is the way the CRM-SIG recommends implementing the .1 properties where implementation environments do not support properties of properties.

**Comment by workergnome** [comment]
Hi there—wrote a response to this problem [in Issue 24](https://github.com/american-art/npg/issues/24#issuecomment-248455308).

**Comment by rhao** [comment]
Resolved with the CRMpc file attached in #24
