### ISSUE TITLE
NPGExhibitionObjXrefs redundant statements

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/npg#6]
NPGExhibitionObjXrefs includes redundant statements:

```
<http://americanartcollaborative.org/npg/object/60> a crm:E22_Man-Made_Object ;
    crm:P12i_was_present_at <http://americanartcollaborative.org/npg/exhibition/738>,
        <http://americanartcollaborative.org/npg/exhibition/874> .
<http://americanartcollaborative.org/npg/exhibition/874> a crm:E7_Activity .
```

It should not produce types, since these are produced by  NPGExhibitions and NPGObjects respectively. It should only produce P12i.

**Comment by YinyiUSC** [comment]
Sorry I am a little confused here. Could you elaborate a bit more on "it should not produce types"? I think in the snippet you gave, the object was present at both exhibition 738 and 874, and then exhibition 874 is characterized as an instance of E7_Activity. I am not sure what the redundancy is.

**Comment by VladimirAlexiev** [comment]
NPGExhibitions makes statements "a crm:E22_Man-Made_Object" and 
NPGObjects makes statements "a crm:E7_Activity".
So NPGExhibitionObjXrefs  shouldn't make such, but only the link (crm:P12i_was_present_at)

**Comment by YinyiUSC** [comment]
Since we need to make the URIs for both objects and exhibitions in the NPGExhibitionObjXrefs, Karma automatically produces "type" statements such as "http://americanartcollaborative.org/npg/object/60 a crm:E22_Man-Made_Object".

**Comment by VladimirAlexiev** [comment]
RDF consists of edges, not nodes (URIs). 
If Karma has such limitation (cannot emit a URI without tacking a type), then ok.

**Comment by szeke** [comment]
Karma always produces rdf:type edges when it produces triples for a URI subject. It does not now that you may be generating the rdf:type in a diferent separate source. The redundant rdf:type statements will coalesce in the triple store.
