### ISSUE TITLE
Blank node in productions

### ISSUE THREAD

**Issue by workergnome** [american-art/npg#65]
IN every object, there are two productions, one of which is a blank node.  This is likely a typo—please verify and correct.

See <http://data.americanartcollaborative.org/page/npg/object/98958> for an example.

**Comment by si-npg** [comment]
Is this something that was wrong with our data?

**Comment by workergnome** [comment]
Doesn't look like it—probably just a mapping typo.

**Comment by bsnikhila** [comment]
Fixed.

**Comment by workergnome** [comment]
Thank you.
