### ISSUE TITLE
(!) strange choice of URL for title

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/npg#67]
http://data.americanartcollaborative.org/page/npg/thesauri/title/williammcchesneymartin

This is an extremely strange choice of URL. You don't put titles in thesauri, you put lookup lists (title type perhaps).
Consider that a common word like "Flowers" could be a primary title of one painting but alternate title of another. You'd map them both to http://data.americanartcollaborative.org/page/npg/thesauri/title/flowers, thus mixing up the title types.

Instead of this, use the object ID and title ID, eg data.americanartcollaborative.org/npg/object/49748/title/23.

Note: using the title type is not good either (see https://github.com/american-art/cbm/issues/58 item 2), eg data.americanartcollaborative.org/npg/object/49748/title/alternate will mix up the values of two alternate titles.

**Comment by VladimirAlexiev** [comment]
CCMA has the same problem: http://data.americanartcollaborative.org/ccma/thesauri/title/stelizabethofhungary

**Comment by VladimirAlexiev** [comment]
GM has the same problem: http://data.americanartcollaborative.org/page/GM/thesauri/title/fromeaarisstonancycrussell

**Comment by bsnikhila** [comment]
Used the Object URI to make Title URIs where Title IDs are not provided.
