### ISSUE TITLE
Production without date

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/npg#71]
@workergnome This query finds Production events without any dates http://yasgui.org/short/B1gzArYne
```
SELECT (count(*) as ?c) ?mus  {
  ?x crm:P52_has_current_owner ?mus; crm:P108i_was_produced_by ?prod
  filter not exists {?prod crm:P4_has_time-span ?y}
  filter not exists {?prod rdfs:label ?y}
} group by ?mus

 "c" , "mus" ,
 "330" , "http://data.americanartcollaborative.org/puam" ,
 "11" , "http://data.americanartcollaborative.org/autry" ,
 "602" , "http://data.americanartcollaborative.org/npg" ,
```
Please check a few in different museums to see if you're ok with it. Checked a few NPG, they got only is_performed_by

**Comment by workergnome** [comment]
If the data's not there, then there's no data—I'm fine with that.  Better than a blank timespan.

**Comment by VladimirAlexiev** [comment]
Check in the source data of PUAM, NPG whether they got no date & place of production

**Comment by workergnome** [comment]
I'm trying _very_ hard not to fall down the rabbit hole of reviewing mappings from the primary source material—it needs to be done, but I'm probably not the right person to be doing it.

**Comment by VladimirAlexiev** [comment]
@kateblanch Can the NPG person do this check?
https://github.com/american-art/PUAM/issues/40 is the corresponding task for PUAM, and shows the query to get the offending object and production URLs.

**Comment by kateblanch** [comment]
@si-npg -- can you check your source data for production events with no dates (i.e. objects with no date created). You can click on this link to see a list of the Object IDs where this seems to be happening:
http://yasgui.org/short/BkpGngn2e

**Comment by si-npg** [comment]
Those objects have no date entered in our database. Begin Date and End Date cannot be null in TMS, so a 0 is automatically inserted for each. The display date field is either blank or has something like "n.d.a." entered.

**Comment by VladimirAlexiev** [comment]
@si-npg Which of the 602 objects did you check?

**Comment by si-npg** [comment]
I checked the first few and then a few random ones. In our collections database, I called up all NPG objects with no dates and got 588 of them, most with nothing in the display field but some with "n.d.a." or "unknown", and a couple with "No date".

**Comment by VladimirAlexiev** [comment]
Thanks @si-npg!
If you've exported all of your objects, close this.
602 is more than 588 but the number is close enough to spend effort chasing why.
If you've exported only a selection, let's chase it.

**Comment by si-npg** [comment]
I queried on objects with the same criteria as those I exported (accessioned objects that are checked for public access.) The small difference in the results represents the additional objects that now have that criteria. So I think we're good.
