### ISSUE TITLE
Problem with NPG data in the Browse App

### ISSUE THREAD

**Issue by si-npg** [american-art/npg#76]
NPG objects with IDs 100697 and 100698 are coming up with no data in the Browse App (and unfortunately they come up first, since there is no title.)

**Comment by si-npg** [comment]
P.S. I'm guessing Classification is the problem, and I can explain the issue if it would help.

**Comment by workergnome** [comment]
It would be helpful to understand this issue.

**Comment by si-npg** [comment]
I did some work on NPG's object classifications last fall, and the updated classification for these two objects is one that I had to add to our classifications authority, as it wasn't yet included. Previously the classification for these objects was "Other". The new classification "Periodical" (and a few other new ones that I also added) was not included in the spreadsheet I had submitted earlier to Kate that linked our classifications to AAT terms. Could this unrecognized classification cause the records to get broken in the browse app? This problem would affect over 70 additional object records in our data set. Should I submit a new classifications spreadsheet? Is that being used for the browse app?

**Comment by workergnome** [comment]
It is being used in the browse app, through the ISI mapping.  You'd have to check with @caknoblock how they'd want a new one submitted, thought

**Comment by caknoblock** [comment]
Please submit a revised spreadsheet with the complete set of classifications.

**Comment by si-npg** [comment]
[Classifications_Updated2017Apr.xlsx](https://github.com/american-art/npg/files/1223332/Classifications_Updated2017Apr.xlsx)

**Comment by kateblanch** [comment]
This remains unresolved - objects still skeletal.
http://data.americanartcollaborative.org/page/npg/object/100697
 Can @caknoblock or @bsnikhila let us know if this data has been refreshed?
