### ISSUE TITLE
NPGObjects:ObjectID

### ISSUE THREAD

**Issue by steads** [american-art/npg#9]
ObjectID: This is a temporary system identifier used to tie records together between files and as such there is no need to map it.

**Comment by azaroth42** [comment]
If it is temporary (and per #10 there is a better identifier) then :+1: to not mapping it.

**Comment by si-npg** [comment]
Correct--no need to map, though very important for record links.

**Comment by rhao** [comment]
Closing this issue because it's discussed in #10
